# A file containing a list of collections to be installed.
# Usage:
# ansible-galaxy install -r requirements.yml
---
collections:
  - name: community.docker
  - name: community.general  # Required for apk, from_ini and supervisorctl modules.
