---
# Molecule configuration file.
# Dependency management (download roles/collections)
# Note: Keep YAML keys sorted alphabetically.
dependency:
  name: galaxy
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  molecule syntax
  ansible-lint
platforms:
  - name: alpine-latest
    image: alpine:3.20
  - name: debian-latest
    image: debian:latest
  - name: nixos-latest
    dockerfile: ../resources/playbooks/Dockerfile.j2
    image: nixos/nix:latest
    pre_build_image: false
  - name: ubuntu-jammy
    image: ubuntu:jammy
  - name: ubuntu-noble
    image: ubuntu:noble
  - name: ubuntu-latest
    image: ubuntu:latest
provisioner:
  config_options:
    defaults:
      host_key_checking: false
      # Use the built-in default callback with result_format instead of community.general.yaml
      result_format: yaml
      stdout_callback: ansible.builtin.default
      verbosity: 1
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"
  inventory:
    group_vars:
      all:
        wine_install_winetricks: true
        wine_install_recommends: true
        wine_release: staging
    host_vars:
      nixos-latest:
        ansible_python_interpreter: /root/.nix-profile/bin/python3
  ssh_connection:
    pipelining: true
  name: ansible
  options:
    diff: true
    force-handlers: true
  playbooks:
    create: ../default/create.yml
    converge: ../default/converge.yml
    cleanup: ../default/cleanup.yml
    side_effect: ../default/side_effect.yml
    prepare: ../default/prepare.yml
    destroy: ../default/destroy.yml
    verify: ../default/verify.yml
  verifier:
    name: ansible
