---
- name: Install Wine on Alpine
  become: true
  community.general.apk:
    name: wine
    state: present
    update_cache: true
- name: Create symbolic link
  become: true
  file:
    src: /usr/bin/wine64
    dest: /usr/bin/wine
    state: link
