---
- name: Ensures Wine is present (Alpine)
  become: true
  ansible.builtin.package:
    name: wine
    state: present
    update_cache: true
- name: Ensures symbolic link for Wine is present
  become: true
  ansible.builtin.file:
    src: /usr/bin/wine64
    dest: /usr/bin/wine
    state: link
  when: false
- name: Ensures Winetricks is present (via URL)
  ansible.builtin.get_url:
    dest: /usr/local/bin/winetricks
    force: false
    mode: 0755
    url: "{{ wine_winetricks_url }}"
  become: true
  when: wine_install_winetricks
- name: Ensures p7zip is present (Alpine)
  become: true
  ansible.builtin.package:
    name: p7zip
    state: present
    update_cache: true
