---
- name: Install Wine on Alpine
  become: true
  ansible.builtin.package:
    name: wine
    state: present
    update_cache: true
- name: Create symbolic link
  become: true
  ansible.builtin.file:
    src: /usr/bin/wine64
    dest: /usr/bin/wine
    state: link
  when: false
- name: Install Winetricks (via URL)
  ansible.builtin.get_url:
    dest: /usr/local/bin/winetricks
    force: false
    mode: 0755
    url: "{{ wine_winetricks_url }}"
  become: true
  when: wine_install_winetricks
