---
- name: Install Wine
  community.general.homebrew_cask:
    name: "{{ item }}"
  with_items:
    - wine-{{ wine_release }}
- name: Install Winetricks
  ansible.builtin.package:
    name: winetricks
  when: wine_install_winetricks
- name: Install p7zip
  ansible.builtin.package:
    name: p7zip
  when: wine_install_p7zip
