---
- name: Install Wine
  community.general.homebrew_cask:
    name: "{{ item }}"
  with_items:
    - wine-{{ wine_release }}
- name: Install Winetricks
  package:
    name: winetricks
  when: wine_install_winetricks
