---
- name: Adds 32-bit architecture dependencies
  ansible.builtin.lineinfile:
    create: true
    dest: /var/lib/dpkg/arch
    line: "{{ item }}"
    mode: 0644
  become: true
  with_items:
    - amd64
    - i386
- name: Add Wine repo
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/winehq.list
    mode: 0644
    src: winehq.{{ ansible_os_family }}.list.j2
  become: true
- name: Install GPG agent (required by apt-key)
  ansible.builtin.apt:
    allow_unauthenticated: !!str yes
    install_recommends: !!str no
    name: "{{ item }}"
    state: present
    update_cache: !!str yes
  become: true
  with_items:
    - gpg
    - gpg-agent
- name: Adds Wine's repo Apt signing key
  ansible.builtin.apt_key:
    id: D43F640145369C51D786DDEA76F1A20FF987672F
    keyring: /etc/apt/trusted.gpg.d/winehq.gpg
    state: present
    url: https://dl.winehq.org/wine-builds/winehq.key
  become: true
- name: Install Wine package
  block:
    - name: Install Wine package (Debian)
      ansible.builtin.apt:
        allow_unauthenticated: !!str yes
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: "{{ item }}"
        state: present
        update_cache: !!str yes
      become: true
      with_items:
        - wine
        - wine32:i386
        - wine64:amd64
      when: lsb_release_dist_id.stdout in ["Debian"]
    - name: Install Wine package (Ubuntu)
      ansible.builtin.apt:
        allow_unauthenticated: !!str yes
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: "{{ item }}"
        state: present
        update_cache: !!str yes
      become: true
      with_items:
        - wine32:i386
        - wine64:amd64
        - wine-stable
      when: lsb_release_dist_id.stdout in ["Ubuntu"]
    - name: Install Wine package (non-Debian)
      ansible.builtin.apt:
        allow_unauthenticated: !!str yes
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: "{{ item }}"
        state: present
        update_cache: !!str yes
      become: true
      with_items:
        - winehq-{{ wine_release }}
      when: lsb_release_dist_id.stdout not in ["Debian", "Ubuntu"]
- name: Install Winetricks
  block:
    - name: Install Winetricks via Apt (Ubuntu)
      ansible.builtin.apt:
        allow_unauthenticated: !!str yes
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: winetricks
        state: present
        update_cache: !!str yes
      become: true
      when: lsb_release_dist_id.stdout in ["Ubuntu"]
    - name: Install Winetricks via URL (non-Ubuntu)
      ansible.builtin.get_url:
        dest: /usr/local/bin/winetricks
        force: false
        mode: 0755
        url: "{{ wine_winetricks_url }}"
      become: true
      when: lsb_release_dist_id.stdout not in ["Ubuntu"]
  when: wine_install_winetricks
