---
- name: Adds 32-bit architecture dependencies
  ansible.builtin.lineinfile:
    create: true
    dest: /var/lib/dpkg/arch
    line: '{{ item }}'
    mode: 0644
  become: true
  with_items:
    - amd64
    - i386
- name: Add Wine repo
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/winehq.list
    mode: 0644
    src: winehq.{{ ansible_os_family }}.list.j2
  become: true
- name: Add Wine backports repo
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/ubuntu.list
    mode: 0644
    src: winehq.Ubuntu.list.j2
  become: true
  when: lsb_release_dist_id.stdout in ["Ubuntu"]
- name: Install GPG agent (required by apt-key)
  ansible.builtin.apt:
    allow_unauthenticated: true
    install_recommends: false
    name: '{{ item }}'
    state: present
    update_cache: true
  become: true
  with_items:
    - gpg
    - gpg-agent
- name: Adds Wine's repo Apt signing key
  ansible.builtin.apt_key:
    id: D43F640145369C51D786DDEA76F1A20FF987672F
    keyring: /etc/apt/trusted.gpg.d/winehq.gpg
    state: present
    url: https://dl.winehq.org/wine-builds/winehq.key
  become: true
- name: Adds Wine's backports repo Apt signing key
  ansible.builtin.apt_key:
    id: BBB8BD3BBE6AD3419048EDC50795A9A788A59C82
    state: present
    url:
      "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xbbb8bd3bbe6ad341\
      9048edc50795a9a788a59c82"
  become: true
- name: Install Wine package
  block:
    - name: Install Wine package (Debian)
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: '{{ item }}'
        state: present
        update_cache: true
      become: true
      with_items:
        - wine
        - wine32:i386
        - wine64:amd64
      when: lsb_release_dist_id.stdout in ["Debian"]
    - name: Install Wine package (Ubuntu)
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: '{{ item }}'
        state: present
        update_cache: true
      become: true
      with_items:
        - wine32:i386
        - wine64:amd64
        - winehq-stable
      when: lsb_release_dist_id.stdout in ["Ubuntu"]
    - name: Install Wine package (non-Debian)
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: '{{ item }}'
        state: present
        update_cache: true
      become: true
      with_items:
        - winehq-{{ wine_release }}
      when: lsb_release_dist_id.stdout not in ["Debian", "Ubuntu"]
