---
- name: Check if Wine is installed
  changed_when: false
  command: which wine
  failed_when: cmd_which_wine_res.rc > 1
  register: cmd_which_wine_res
- name: Install Wine
  block:
    - name: Get code name of the distribution
      changed_when: false
      command: /usr/bin/lsb_release -sc
      register: lsb_release_code_name
      when: ansible_os_family in ["Debian"]
    - name: Get ID of the distribution
      changed_when: false
      command: /usr/bin/lsb_release -si
      register: lsb_release_dist_id
      when: ansible_os_family in ["Debian"]
    - name: Include operating system specific tasks
      include_tasks:
        file: "{{ ansible_os_family }}.yml"
  when: cmd_which_wine_res.rc != 0
- name: Verify Wine command
  changed_when: false
  command: wine --version
