---
- name: Checks if Wine is installed
  ansible.builtin.command: wine --version
  check_mode: false
  changed_when: false
  register: cmd_wine_version
  failed_when: cmd_wine_version.rc != 0 and cmd_wine_version.rc != -6

- name: Checks if Winetricks is installed
  changed_when: false
  ansible.builtin.command: winetricks --version
  when: wine_install_winetricks

- name: Checks if required tools are installed
  changed_when: false
  ansible.builtin.command: "{{ wine_package_command_map[item] | default(item) }} --version"
  loop: "{{ wine_install_winetricks_dependencies }}"
  register: dependency_check_results
  failed_when: false
  when:
    - wine_install_winetricks
    - wine_install_winetricks_dependencies | length > 0

- name: Verify dependency installation status
  ansible.builtin.assert:
    that: >-
      dependency_check_results.results |
      selectattr('rc', 'eq', 0) |
      list |
      length == wine_install_winetricks_dependencies | length
    fail_msg: "Some winetricks dependencies failed verification"
    success_msg: "All winetricks dependencies successfully verified"
  when:
    - wine_install_winetricks
    - wine_install_winetricks_dependencies | length > 0
