---
- name: Checks if Wine is installed
  ansible.builtin.command: wine --version
  check_mode: false
  changed_when: false
  register: cmd_wine_version
  failed_when: cmd_wine_version.rc != 0 and cmd_wine_version.rc != -6

- name: Checks if Winetricks is installed
  changed_when: false
  ansible.builtin.command: winetricks --version
  register: cmd_winetricks_version
  failed_when: cmd_winetricks_version.rc != 0 and cmd_winetricks_version.rc != -6
  when: wine_install_winetricks | bool

- name: Verify dependency installation status
  when:
    - wine_install_winetricks | bool
    - wine_install_winetricks_dependencies | length > 0
  block:
    - name: Check if required tools are installed
      ansible.builtin.command: which "{{ wine_package_command_map[item] | default(item) }}"
      changed_when: false
      register: dependency_check_results
      loop: "{{ wine_install_winetricks_dependencies }}"
      failed_when: false

    - name: Display dependency check results (debug)
      ansible.builtin.debug:
        msg: "Dependency check for {{ item.item }}: {{ 'Successful' if item.rc == 0 else 'Failed' }}"
      loop: "{{ dependency_check_results.results }}"
      when: ansible_verbosity > 0

    - name: Verify dependency installation status (with improved checking)
      ansible.builtin.assert:
        that: >-
          dependency_check_results.results |
          selectattr('rc', 'eq', 0) |
          list |
          length == (wine_install_winetricks_dependencies | length)
        fail_msg: >-
          Some winetricks dependencies failed verification.
          Please install:
          {{ dependency_check_results.results |
             selectattr('rc', 'ne', 0) |
             map(attribute='item') |
             list |
             join(', ') }}
        success_msg: "All winetricks dependencies successfully verified"
