---
- name: Includes operating system specific tasks ({{ ansible_os_family }})
  ansible.builtin.include_tasks:
    file: "wine-{{ ansible_os_family }}.yml"

- name: Install dependencies required by winetricks ({{ ansible_os_family }})
  ansible.builtin.include_tasks:
    file: install-deps-{{ ansible_os_family }}.yml
  when:
    - wine_install_winetricks
