---
- name: Get ID of the distribution
  changed_when: false
  ansible.builtin.command: /usr/bin/lsb_release -si
  register: lsb_release_dist_id
  when: ansible_os_family in ["Debian"]
- name: Install Winetricks via Apt (Ubuntu)
  ansible.builtin.apt:
    allow_unauthenticated: true
    install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
    name: winetricks
    state: present
    update_cache: true
  become: true
  when:
    - lsb_release_dist_id.stdout is defined
    - lsb_release_dist_id.stdout in ["Ubuntu"]
- name: Install Winetricks via URL
  ansible.builtin.get_url:
    dest: /usr/local/bin/winetricks
    force: false
    mode: 0755
    url: '{{ wine_winetricks_url }}'
  become: true
  when: >-
    (lsb_release_dist_id.stdout is not defined
    or lsb_release_dist_id.stdout not in ["Ubuntu"])
