---
- name: Get code name of the distribution
  changed_when: false
  ansible.builtin.command: /usr/bin/lsb_release -sc
  register: lsb_release_code_name
  when: ansible_os_family in ["Debian"]
- name: Get ID of the distribution
  changed_when: false
  ansible.builtin.command: /usr/bin/lsb_release -si
  register: lsb_release_dist_id
  when: ansible_os_family in ["Debian"]
- name: Include operating system specific tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_os_family }}.yml"
