---
- name: Ensures that winetricks dependencies are installed
  become: "{{ ansible_user_id != 'root' }}"
  become_method: >-
    {{ wine_become_method.get(detected_os_family | default(ansible_os_family),
    wine_become_method["_default"]) }}
  block:

    - name: Check if Nix store exists
      ansible.builtin.stat:
        path: /nix/store
      register: nix_store_stat

    - name: Get HOME of the privileged user
      ansible.builtin.command: echo $HOME
      register: privileged_home
      changed_when: false
      check_mode: false

    - name: Ensures dependencies are present
      ansible.builtin.command:
        cmd: nix-env -iA nixpkgs.{{ item }}
        creates: "{{ privileged_home.stdout }}/.nix-profile/bin/{{ item }}"
      loop: "{{ wine_install_winetricks_dependencies }}"
      when: nix_store_stat.stat.exists
