---
- name: Ensures that dependencies are installed
  become: "{{ ansible_user_id != 'root' }}"
  block:

    - name: Ensure required packages are present
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: false
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: "{{ wine_install_winetricks_dependencies }}"

- name: Apt cleanup
  become: true
  when: wine_install_winetricks
  block:

    - name: Removes dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
        purge: true

    - name: Cleans Apt cache
      ansible.builtin.apt:
        autoclean: true
        clean: true
