---
- name: Ensure Winetricks dependencies via Homebrew
  become: "{{ ansible_user_id != 'root' }}"
  become_method: ansible.builtin.su
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ wine_install_winetricks_dependencies }}"
  when: wine_install_winetricks | bool
