---
- name: Ensures that winetricks dependencies are installed
  become: "{{ ansible_user_id != 'root' }}"
  become_method: >-
    {{ wine_become_method.get(detected_os_family | default(ansible_os_family),
    wine_become_method["_default"]) }}
  block:

    - name: Check if Nix store exists
      ansible.builtin.stat:
        path: /nix/store
      register: nix_store_stat

    - name: Get HOME of the privileged user
      ansible.builtin.command: printenv HOME
      register: privileged_home
      changed_when: false
      check_mode: false

    - name: Ensures dependencies are present
      ansible.builtin.shell: |
        set -euo pipefail
        {% if wine_package_command_map[item] | default('') | length > 0 %}
        if [ -f "{{ privileged_home.stdout }}/.nix-profile/bin/{{ wine_package_command_map[item] }}" ]; then
          echo "Package {{ item }} already present via binary check."
          exit 0
        fi
        {% endif %}
        if nix-env -q | grep -qE "^{{ item }}-|^nixpkgs.{{ item }}$"; then
          echo "Package {{ item }} already present via nix-env -q."
          exit 0
        fi
        nix-env -iA nixpkgs.{{ item }}
      loop: "{{ wine_winetricks_dependencies_os_family['NixOS'] | default(wine_install_winetricks_dependencies) }}"
      register: nix_install
      changed_when: "'installing' in nix_install.stdout or 'building' in nix_install.stdout"
      when: nix_store_stat.stat.exists
