---
- name: Ensures that dependencies are installed
  become: "{{ ansible_user_id != 'root' }}"
  become_method: "{{ wine_become_method }}"
  block:

    - name: Install winetricks dependencies (Alpine)
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ wine_install_winetricks_dependencies }}"
