---
- name: Ensures that winetricks dependencies are installed
  become: "{{ ansible_user_id != 'root' }}"
  block:

    - name: Check if Nix store exists
      ansible.builtin.stat:
        path: /nix/store
      register: nix_store_stat

    - name: Ensures dependencies are present
      ansible.builtin.command:
        cmd: nix-env -iA nixpkgs.{{ item }}
        creates: "{{ ansible_env.HOME }}/.nix-profile/bin/{{ item }}"
      loop: "{{ wine_install_winetricks_dependencies }}"
      when: nix_store_stat.stat.exists
