---
- name: Ensures winetricks and dependencies are present
  become: "{{ ansible_user_id != 'root' }}"
  become_method: "{{ wine_become_method[ansible_os_family] | default(wine_become_method['_default']) }}"
  when: wine_install_winetricks | bool
  block:

    - name: Ensures winetricks is present ({{ ansible_os_family }})
      ansible.builtin.include_tasks:
        apply:
          tags: winetricks
        file: "winetricks-{{ ansible_os_family }}.yml"
      tags: winetricks

    - name: Install dependencies required by winetricks ({{ ansible_os_family }})
      ansible.builtin.include_tasks:
        apply:
          tags: winetricks-deps
        file: install-deps-{{ ansible_os_family }}.yml
      tags: winetricks-deps
      when:
        - wine_install_winetricks_dependencies | length > 0
