---
- name: Ensures winetricks and dependencies are present
  become: "{{ ansible_user_id != 'root' }}"
  become_method: >-
    {{ wine_become_method.get(detected_os_family | default(ansible_os_family),
    wine_become_method["_default"]) }}
  when: wine_install_winetricks | bool
  block:

    - name: Ensures winetricks is present ({{ detected_os_family | default(ansible_os_family) }})
      ansible.builtin.include_tasks:
        apply:
          tags: winetricks
        file: >-
          winetricks-{{
          'Debian' if (detected_os_family | default(ansible_os_family)) == 'Ubuntu'
          else (detected_os_family | default(ansible_os_family)) }}.yml
      tags: winetricks

    - name: Install dependencies required by winetricks ({{ detected_os_family | default(ansible_os_family) }})
      ansible.builtin.include_tasks:
        apply:
          tags: winetricks-deps
        file: >-
          install-deps-{{
          'Debian' if (detected_os_family | default(ansible_os_family)) == 'Ubuntu'
          else (detected_os_family | default(ansible_os_family)) }}.yml
      tags: winetricks-deps
      when:
        - wine_selected_winetricks_dependencies | length > 0
