---
- name: Check for NixOS (via nix-env command)
  ansible.builtin.command: which nix-env
  register: nixos_check
  changed_when: false
  failed_when: false

- name: Set detected OS family for task inclusion
  ansible.builtin.set_fact:
    detected_os_family: "{{ 'NixOS' if (nixos_check.rc == 0) else ansible_facts['os_family'] }}"
    cacheable: true

- name: Ensures winetricks and dependencies are present
  become: "{{ ansible_user_id != 'root' }}"
  become_method: '{{ wine_become_method.get(detected_os_family, wine_become_method["_default"]) }}'
  when: wine_install_winetricks | bool
  block:

    - name: Ensures winetricks is present ({{ detected_os_family }})
      ansible.builtin.include_tasks:
        apply:
          tags: winetricks
        file: 'winetricks-{{ detected_os_family }}.yml'
      tags: winetricks

    - name: Install dependencies required by winetricks ({{ detected_os_family }})
      ansible.builtin.include_tasks:
        apply:
          tags: winetricks-deps
        file: 'install-deps-{{ detected_os_family }}.yml'
      tags: winetricks-deps
      when:
        - wine_install_winetricks_dependencies | length > 0
