---
- name: Ensures winetricks is present ({{ ansible_os_family }})
  become: "{{ ansible_user_id != 'root' }}"
  block:

    - name: Ensures Winetricks is present (via URL)
      ansible.builtin.get_url:
        dest: /usr/local/bin/winetricks
        force: false
        mode: "0755"
        url: "{{ wine_winetricks_url }}"
      become: true
      when: wine_install_winetricks
