---
- name: >-
    Ensures winetricks is present
    ({{ wine_detected_os_family | default(ansible_facts.get(
    'os_family', ansible_os_family | default('Alpine')), true) }})
  become: "{{ ansible_facts.get('user_id', 'root') != 'root' }}"
  become_method: >-
    {{ wine_become_method.get(wine_detected_os_family | default(ansible_facts.get('os_family')),
    wine_become_method["_default"]) }}
  block:

    - name: Ensures Winetricks is present (via URL)
      ansible.builtin.get_url:
        dest: /usr/local/bin/winetricks
        force: false
        mode: "0755"
        url: "{{ wine_winetricks_url }}"
      become: true
      when: wine_install_winetricks | bool
