---
- name: Ensures Wine is present (Homebrew Cast)
  become: "{{ ansible_user_id is defined and ansible_user_id != 'root' }}"
  become_method: >-
    {{ wine_become_method.get(detected_os_family | default(ansible_os_family),
    wine_become_method["_default"]) }}
  block:
    - name: Ensures Wine is present (Homebrew Cast)
      community.general.homebrew_cask:
        name: "wine-{{ wine_release }}{% if wine_version %}-{{ wine_version }}{% endif %}"
