---
- name: Ensures Wine is present
  become: true
  block:

    - name: Ensures Wine is present ({{ ansible_os_family }})
      become: true
      ansible.builtin.package:
        name: wine
        state: present
        update_cache: true
