---
- name: Ensures Wine repository is configured
  become: >
    {{ (ansible_facts['user_id'] is defined and ansible_facts['user_id'] != 'root')
    or (lookup('env', 'UID') | int != 0) }}
  become_method: >
    {{ wine_become_method.get(ansible_facts["os_family"],
    wine_become_method["_default"]) }}
  block:
    - name: Ensures lsb_release command is present
      ansible.builtin.package:
        name: lsb-release
        state: present
    - name: Gets code name of the distribution
      changed_when: false
      ansible.builtin.command: /usr/bin/lsb_release -sc
      become: false
      register: lsb_release_code_name
    - name: Gets ID of the distribution
      changed_when: false
      ansible.builtin.command: /usr/bin/lsb_release -si
      become: false
      register: lsb_release_dist_id
    - name: Adds architecture dependencies
      ansible.builtin.lineinfile:
        create: true
        dest: /var/lib/dpkg/arch
        line: '{{ item }}'
        mode: "0644"
      with_items:
        - amd64
        - i386
    - name: Ensures Apt cache is up-to-date
      ansible.builtin.apt:
        update_cache: true
    - name: Ensures CA certificates are installed
      ansible.builtin.apt:
        name: ca-certificates
        state: present
    - name: Ensures GPG key directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
    - name: Download Wine's repo GPG key
      ansible.builtin.get_url:
        url: https://dl.winehq.org/wine-builds/winehq.key
        dest: /etc/apt/keyrings/winehq-archive-keyring.asc
        mode: "0644"
    - name: Ensures Wine repo is present
      ansible.builtin.template:
        dest: /etc/apt/sources.list.d/winehq.list
        mode: "0644"
        src: 'winehq.{{ ansible_facts["os_family"] }}.list.j2'
    - name: Ensures Wine backports repo is present
      ansible.builtin.template:
        dest: /etc/apt/sources.list.d/ubuntu.list
        mode: "0644"
        src: winehq.Ubuntu.list.j2
      when:
        - lsb_release_dist_id.stdout in ["Ubuntu"]
    - name: Download Ubuntu backports GPG key
      ansible.builtin.get_url:
        url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xbbb8bd3bbe6ad3419048edc50795a9a788a59c82"
        dest: /etc/apt/keyrings/ubuntu-backports-keyring.asc
        mode: "0644"
      when:
        - lsb_release_dist_id.stdout in ["Ubuntu"]

- name: Ensures Wine is present
  become: >
    {{ (ansible_facts['user_id'] is defined and ansible_facts['user_id'] != 'root')
    or (lookup('env', 'UID') | int != 0) }}
  block:
    - name: Ensures Wine package is present (Debian)
      ansible.builtin.apt:
        allow_unauthenticated: true
        autoclean: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: '{{ item }}'
        state: present
        update_cache: true
      with_items:
        - wine
        - wine32:i386
        - wine64
      when: lsb_release_dist_id.stdout in ["Debian"]
    - name: Ensures Wine package is present (Ubuntu)
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: '{{ item }}'
        state: present
        update_cache: true
      with_items:
        - winehq-{{ wine_release }}
      when: lsb_release_dist_id.stdout in ["Ubuntu"]
    - name: Ensures Wine package is present (non-Debian)
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: '{{ item }}'
        state: present
        update_cache: true
      with_items:
        - winehq-{{ wine_release }}
      when: lsb_release_dist_id.stdout not in ["Debian", "Ubuntu"]
    - name: Ensures p7zip package is present
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: p7zip-full
        state: present
        update_cache: true

- name: Ensures ~/.wine is initialized
  ansible.builtin.command: wineboot -u
  environment:
    WINEARCH: win64
  changed_when: false

- name: Apt cleanup ({{ ansible_facts["os_family"] }})
  become: >
    {{ (ansible_facts['user_id'] is defined and ansible_facts['user_id'] != 'root')
    or (lookup('env', 'UID') | int != 0) }}
  when: wine_install_winetricks | bool
  block:

    - name: Removes dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
        purge: true

    - name: Cleans Apt cache
      ansible.builtin.apt:
        autoclean: true
        clean: true
