---
- name: Ensures Wine is present (Homebrew Cast)
  become: "{{ ansible_facts['user_id'] is defined and ansible_facts['user_id'] != 'root' }}"
  become_method: ansible.builtin.sudo
  block:
    - name: Ensures Wine is present (Homebrew Cast)
      community.general.homebrew_cask:
        name: "wine-{{ wine_release }}{% if wine_version %}-{{ wine_version }}{% endif %}"
