---
- name: Ensures Wine repository is configured
  become: true
  block:
    - name: Ensures lsb_release command is present
      ansible.builtin.package:
        name: lsb-release
        state: present
    - name: Gets code name of the distribution
      changed_when: false
      ansible.builtin.command: /usr/bin/lsb_release -sc
      become: false
      register: lsb_release_code_name
    - name: Gets ID of the distribution
      changed_when: false
      ansible.builtin.command: /usr/bin/lsb_release -si
      become: false
      register: lsb_release_dist_id
    - name: Adds architecture dependencies
      ansible.builtin.lineinfile:
        create: true
        dest: /var/lib/dpkg/arch
        line: '{{ item }}'
        mode: "0644"
      with_items:
        - amd64
        - i386
    - name: Ensures Apt cache is up-to-date
      ansible.builtin.apt:
        update_cache: true
    - name: Ensures Wine repo is present
      ansible.builtin.template:
        dest: /etc/apt/sources.list.d/winehq.list
        mode: "0644"
        src: winehq.{{ ansible_os_family }}.list.j2
    - name: Ensures GPG agent is present (required by apt-key)
      ansible.builtin.package:
        name: '{{ item }}'
        state: present
      with_items:
        - gpg
        - gpg-agent
    - name: Ensures Wine's repo Apt signing key is present
      ansible.builtin.apt_key:
        id: D43F640145369C51D786DDEA76F1A20FF987672F
        keyring: /etc/apt/trusted.gpg.d/winehq.gpg
        state: present
        url: https://dl.winehq.org/wine-builds/winehq.key
    - name: Ensures Wine backports repo is present
      ansible.builtin.template:
        dest: /etc/apt/sources.list.d/ubuntu.list
        mode: "0644"
        src: winehq.Ubuntu.list.j2
      when:
        - lsb_release_dist_id.stdout in ["Ubuntu"]
    - name: Ensures Wine's backports repo Apt signing key is present
      ansible.builtin.apt_key:
        id: BBB8BD3BBE6AD3419048EDC50795A9A788A59C82
        state: present
        url:
          "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xbbb8bd3bbe6ad341\
          9048edc50795a9a788a59c82"
      when:
        - lsb_release_dist_id.stdout in ["Ubuntu"]
- name: Ensures Wine is present
  become: true
  block:
    - name: Ensures Wine package is present (Debian)
      ansible.builtin.apt:
        allow_unauthenticated: true
        autoclean: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: '{{ item }}'
        state: present
        update_cache: true
      with_items:
        - wine
        - wine32:i386
        - wine64
      when: lsb_release_dist_id.stdout in ["Debian"]
    - name: Ensures Wine package is present (Ubuntu)
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: '{{ item }}'
        state: present
        update_cache: true
      with_items:
        - winehq-{{ wine_release }}
      when: lsb_release_dist_id.stdout in ["Ubuntu"]
    - name: Ensures Wine package is present (non-Debian)
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: '{{ item }}'
        state: present
        update_cache: true
      with_items:
        - winehq-{{ wine_release }}
      when: lsb_release_dist_id.stdout not in ["Debian", "Ubuntu"]
    - name: Ensures p7zip package is present
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: p7zip-full
        state: present
        update_cache: true

- name: Ensures ~/.wine is initialized
  ansible.builtin.command: wineboot -u
  environment:
    WINEARCH: win64
  changed_when: false
- name: Ensures Winetricks is installed
  become: true
  when: wine_install_winetricks
  block:
    - name: Ensures Winetricks is present (Ubuntu)
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: "{{ 'yes' if wine_install_recommends else 'no' }}"
        name: winetricks
        state: present
        update_cache: true
      when: lsb_release_dist_id.stdout in ["Ubuntu"]
    - name: Ensures Winetricks is present via URL
      ansible.builtin.get_url:
        dest: /usr/local/bin/winetricks
        force: false
        mode: "0755"
        url: '{{ wine_winetricks_url }}'
      when:
        - wine_winetricks_url is defined
        - wine_winetricks_url | length > 0
    - name: Ensures Curl is present (required by winetricks)
      ansible.builtin.apt:
        allow_unauthenticated: true
        install_recommends: false
        name: curl
        state: present
        update_cache: true

- name: Apt cleanup
  become: true
  when: wine_install_winetricks
  block:

    - name: Removes dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
        purge: true

    - name: Cleans Apt cache
      ansible.builtin.apt:
        autoclean: true
        clean: true
