---
- name: Ensures Wine is present
  become: true
  block:

    - name: Ensures Wine is present ({{ ansible_os_family }})
      become: true
      ansible.builtin.package:
        name: wine
        state: present
        update_cache: true

    - name: Ensures Winetricks is present (via URL)
      ansible.builtin.get_url:
        dest: /usr/local/bin/winetricks
        force: false
        mode: "0755"
        url: "{{ wine_winetricks_url }}"
      become: true
      when: wine_install_winetricks
