---
- name: Ensures Wine repository is configured
  become: >-
    {{ ansible_facts.get('user_id', 'root') != 'root' or
    ansible_facts.get('env', {}).get('UID', lookup('ansible.builtin.env', 'UID') | default(0)) | int != 0 }}
  become_method: >-
    {{ wine_become_method.get(wine_detected_os_family | default(ansible_facts.get('os_family')),
    wine_become_method["_default"]) }}
  environment:
    DEBIAN_FRONTEND: noninteractive
  block:
    - name: Ensures Apt cache is up-to-date
      ansible.builtin.apt:
        update_cache: true
      no_log: "{{ wine_no_log }}"
    - name: Ensures basic dependencies are present
      ansible.builtin.package:
        name:
          - ca-certificates
          - lsb-release
        state: present
      no_log: "{{ wine_no_log }}"
    - name: Ensures CA certificates are updated
      ansible.builtin.command: update-ca-certificates
      changed_when: false
    - name: Gets code name of the distribution
      changed_when: false
      ansible.builtin.command: /usr/bin/lsb_release -sc
      become: false
      register: lsb_release_code_name
    - name: Gets ID of the distribution
      changed_when: false
      ansible.builtin.command: /usr/bin/lsb_release -si
      become: false
      register: lsb_release_dist_id
    - name: Adds architecture dependencies
      ansible.builtin.lineinfile:
        create: true
        dest: /var/lib/dpkg/arch
        line: '{{ item }}'
        mode: "0644"
      with_items:
        - amd64
        - i386
    - name: Ensures GPG key directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
    - name: Download Wine's repo GPG key
      ansible.builtin.get_url:
        url: https://dl.winehq.org/wine-builds/winehq.key
        dest: /etc/apt/keyrings/winehq-archive-keyring.asc
        mode: "0644"
    - name: Ensures Wine repo is present
      ansible.builtin.template:
        dest: /etc/apt/sources.list.d/winehq.list
        mode: "0644"
        src: "winehq.{{ ansible_facts.get('os_family') }}.list.j2"
    - name: Ensures Wine backports repo is present
      ansible.builtin.template:
        dest: /etc/apt/sources.list.d/ubuntu.list
        mode: "0644"
        src: winehq.Ubuntu.list.j2
      when:
        - lsb_release_dist_id.stdout in ["Ubuntu"]
    - name: Download Ubuntu backports GPG key
      ansible.builtin.get_url:
        url: >-
          https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0xbbb8bd3bbe6ad3419048edc50795a9a788a59c82
        dest: /etc/apt/keyrings/ubuntu-backports-keyring.asc
        mode: "0644"
      when:
        - lsb_release_dist_id.stdout in ["Ubuntu"]
    - name: Update Apt cache after adding Wine repositories
      ansible.builtin.apt:
        update_cache: true
      no_log: "{{ wine_no_log }}"

- name: Ensures Wine is present
  become: >-
    {{ ansible_facts.get('user_id', 'root') != 'root' or
    ansible_facts.get('env', {}).get('UID', lookup('ansible.builtin.env', 'UID') | default(0)) | int != 0 }}
  become_method: >-
    {{ wine_become_method.get(wine_detected_os_family | default(ansible_facts.get('os_family')),
    wine_become_method["_default"]) }}
  environment:
    DEBIAN_FRONTEND: noninteractive
  block:
    - name: Set wine package name for Ubuntu
      ansible.builtin.set_fact:
        wine_ubuntu_version: >-
          {% set raw_wine_version = wine_version | default('') | string -%}
          {% if raw_wine_version -%}
          {%- if raw_wine_version is search('~') -%}
          {{ raw_wine_version }}{%- else -%}
          {%- set version_parts = raw_wine_version.split('.') -%}
          {{ (version_parts + ['0', '0', '0', '0'])[:4] | join('.') }}~{{
          wine_release_codename or lsb_release_code_name.stdout }}-1{%- endif -%}
          {%- endif %}
    - name: Debug wine_ubuntu_version
      ansible.builtin.debug:
        msg: >-
          wine_version={{ wine_version }},
          wine_release_codename={{ wine_release_codename }},
          computed wine_ubuntu_version={{ wine_ubuntu_version }}
        verbosity: 1
    - name: Set wine package name
      ansible.builtin.set_fact:
        wine_package_name: >-
          {% if wine_ubuntu_version -%}
          winehq-{{ wine_release }}={{ wine_ubuntu_version }}{%- else -%}
          winehq-{{ wine_release }}{%- endif %}
    - name: Debug wine package name
      ansible.builtin.debug:
        msg: "Installing wine package: {{ wine_package_name }}"
        verbosity: 1
    - name: Ensures Wine package and dependencies are present
      ansible.builtin.apt:
        allow_downgrade: true
        install_recommends: "{{ wine_install_recommends | bool }}"
        name: >-
          {{
            [
              wine_package_name,
              "wine-" ~ wine_release ~ ("=" ~ wine_ubuntu_version if wine_ubuntu_version else ""),
              "wine-" ~ wine_release ~ "-amd64" ~ ("=" ~ wine_ubuntu_version if wine_ubuntu_version else ""),
              "wine-" ~ wine_release ~ "-i386:i386" ~ ("=" ~ wine_ubuntu_version if wine_ubuntu_version else "")
            ] + wine_selected_winetricks_dependencies
          }}
        state: present
        update_cache: true
      register: wine_pkg_install_res
      until: wine_pkg_install_res is success
      retries: 3
      delay: 5
      no_log: "{{ wine_no_log }}"

    - name: Ensures ~/.wine is initialized
      ansible.builtin.command: xvfb-run -a wineboot --init
      become: false
      environment:
        HOME: "{{ ansible_facts.get('user_dir', lookup('ansible.builtin.env', 'HOME')) }}"
        WINEDEBUG: "{{ wine_debug | default('-all') }}"
        WINEDLLOVERRIDES: "{{ wine_dlloverrides | default('mscoree,mshtml=') }}"
      args:
        creates: >-
          {{ ansible_facts.get('user_dir', lookup('ansible.builtin.env', 'HOME')) }}/.wine/system.reg
      timeout: 120

- name: Apt cleanup ({{ wine_detected_os_family | default(ansible_facts.get('os_family')) }})
  become: >-
    {{ ansible_facts.get('user_id', 'root') != 'root' or
    ansible_facts.get('env', {}).get('UID', lookup('ansible.builtin.env', 'UID') | default(0)) | int != 0 }}
  become_method: >-
    {{ wine_become_method.get(wine_detected_os_family | default(ansible_facts.get('os_family')),
    wine_become_method["_default"]) }}
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: wine_install_winetricks | bool
  block:

    - name: Removes dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
        purge: true
      when: wine_apt_cleanup | default(false) | bool
      changed_when: false
      no_log: "{{ wine_no_log }}"

    - name: Cleans Apt cache
      ansible.builtin.apt:
        autoclean: true
        clean: true
      when: wine_apt_cleanup | default(false) | bool
      changed_when: false
      no_log: "{{ wine_no_log }}"
