---
- name: Check if Nix store exists
  ansible.builtin.stat:
    path: /nix/store
  register: nix_store_stat

- name: Ensure Wine is installed (Nix)
  become: "{{ ansible_user_id != 'root' }}"
  become_method: "{{ wine_become_method[ansible_os_family] }}"
  block:

    - name: Check if Wine is already installed
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          nix-env -q | grep -qw wine
      changed_when: false
      failed_when: wine_check.rc not in [0, 1]
      register: wine_check
      when: nix_store_stat.stat.exists

    - name: Set wine_pkg fact
      ansible.builtin.set_fact:
        wine_pkg: "{{ 'wine' ~ ('-staging' if wine_release == 'staging' else '') }}"
      when:
        - nix_store_stat.stat.exists
        - wine_check.rc != 0
    - name: Ensure Wine package is installed on Nix image
      ansible.builtin.command: >-
        nix-env -iA nixpkgs.{{ wine_pkg }}
      when:
        - nix_store_stat.stat.exists
        - wine_check.rc != 0
      register: wine_install
      changed_when: wine_install.rc == 0
