---
- name: Ensures Wine is present
  become: "{{ (ansible_user_id is defined and ansible_user_id != 'root') or (lookup('env', 'UID') | int != 0) }}"
  become_method: "{{ wine_become_method.get(ansible_os_family, wine_become_method['_default']) }}"
  block:

    - name: Ensures Wine is present ({{ ansible_os_family }})
      ansible.builtin.package:
        name: wine
        state: present
        update_cache: true
