---
# Vars file for wine role.
# 'wine_become_method' is expected to be a dictionary keyed by OS family (e.g., 'Debian', 'RedHat'),
# where each key maps to the appropriate become method (e.g., 'sudo', 'su') for that OS family.
# Note: Keep YAML keys sorted alphabetically.
wine_become_method:
  _default: ansible.builtin.sudo
  Alpine: ansible.builtin.su
  Darwin: ansible.builtin.sudo
  Debian: ansible.builtin.su
  NixOS: ansible.builtin.su
  OtherLinux: ansible.builtin.su
  Ubuntu: ansible.builtin.sudo
  Windows: ansible.builtin.runas
# This maps package names to their respective commands
# Used to verify dependencies are correctly installed
wine_package_command_map:
  cabextract: cabextract
  curl: curl
  gawk: awk
  p7zip: 7z
  unzip: unzip

# Fontconfig configuration
wine_fontconfig_cache_dir: ".cache/fontconfig"
wine_fontconfig_config_dir: ".config/fontconfig"
wine_fontconfig_config_file: ".config/fontconfig/fonts.conf"
wine_fontconfig_fonts_dirs:
  - ".fonts"
  - ".local/share/fonts"
wine_fontconfig_system_fonts_dir: "/usr/share/fonts"
wine_fontconfig_system_config_file: "/etc/fonts/fonts.conf"
wine_fontconfig_system_config_path: "/etc/fonts"
