---
# 'wine_become_method' is expected to be a dictionary keyed by OS family (e.g., 'Debian', 'RedHat'),
# where each key maps to the appropriate become method (e.g., 'sudo', 'su') for that OS family.
wine_become_method:
  _default: ansible.builtin.sudo
  Alpine: ansible.builtin.su
  Darwin: ansible.builtin.sudo
  Debian: ansible.builtin.su
  OtherLinux: ansible.builtin.su
  Ubuntu: ansible.builtin.su
  Windows: ansible.builtin.runas
# This maps package names to their respective commands
# Used to verify dependencies are correctly installed
wine_package_command_map:
  p7zip: 7z
  curl: curl
  gawk: awk
