---
- name: Prepare hosts
  hosts: "all:!nixos*"
  gather_facts: false
  tasks:

    - name: Install Python for Ansible
      become: "{{ (ansible_user_id is defined and ansible_user_id != 'root') or (lookup('env', 'UID') | int != 0) }}"
      become_method: ansible.builtin.su
      ansible.builtin.raw: |
        command -v python3 || command -v python || (apt -y update && apt install -y python3-minimal)
      changed_when: false

- name: Prepare NixOS hosts
  hosts: "nixos.*"
  gather_facts: false
  tasks:
    # Install Python 3 if not present
    - name: Ensure Python is present for NixOS
      ansible.builtin.raw: |
        if ! command -v python3 &> /dev/null; then
          nix-env -i python3
        fi
      changed_when: false
