---
- name: Verify
  hosts: all
  tasks:
    - name: Verify Wine command
      changed_when: false
      command: wine --version
      register: wine_version
      failed_when: wine_version.rc != 0 and wine_version.rc != -6
    - name: Verify Winetricks command
      changed_when: false
      command: winetricks --version
      when: wine_install_winetricks
