---
- name: Verify
  hosts: all
  tasks:
    - name: Verify Wine command
      changed_when: false
      command: wine --version
    - name: Verify Winetricks command
      changed_when: false
      command: winetricks --version
      when: wine_install_winetricks
