---
# Note: Keep keys and envs in alphabetical order.
name: Check

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 1  # Run every Monday at 00:00 UTC
  workflow_call:
    inputs:
      submodules:
        default: 'false'
        description: Whether to checkout submodules
        required: false
        type: string
  workflow_dispatch:
    inputs:
      submodules:
        default: 'false'
        description: Whether to checkout submodules
        options:
          - 'false'
          - 'true'
          - recursive
        required: false
        type: choice

permissions:
  contents: read

jobs:
  check:
    uses: EA31337/.github/.github/workflows/check.yml@master
    with:
      submodules: ${{ inputs.submodules || 'false' }}
    secrets: inherit
