---
# Note: Keep keys and envs in alphabetical order.
name: Docker Publish

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r .devcontainer/requirements.txt

      - name: Render Dockerfile
        run: jinja2 Dockerfile.j2 -D docker_image='ubuntu:noble' > Dockerfile

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        env:
          IS_DEFAULT_BRANCH: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'push' && env.IS_DEFAULT_BRANCH == 'true' }}
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Test Docker image
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)
          docker pull "$TAG"
          docker run --rm "$TAG" wine --version
