---
name: reviewdog

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
      - name: Add Problem Matcher for actionlint
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
        shell: bash
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.github_token }}
          level: error
          reporter: github-pr-review
